version: "2"

services:
  api:
    build:
      context: .
      args:
        NODE_ENV: "production"
        PORT: 3000
    container_name: aroydee-homepage
    env_file: .env
    ports:
      - 3000:3000
